{% set name = "coldtype" %}
{% set version = "0.10.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coldtype-{{ version }}.tar.gz
  sha256: 32881c4fc4db0e90f4419700f3cbd41c866af6434aeadb81954db1cc710d3541

build:
  entry_points:
    - coldtype = coldtype.renderer:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - blackrenderer >=0.6.0
    - fonttools
    - fontpens
    - easing-functions
    - mido
    - defcon
    - freetype-py
    - uharfbuzz >=0.14.0
    - python-bidi
    - requests
    - b3denv >=0.0.5

test:
  imports:
    - coldtype
  commands:
    - pip check
    - coldtype --help
  requires:
    - pip

about:
  home: https://github.com/goodhertz/coldtype
  summary: Functions for manual vectorized typesetting
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
