schema_version: 1

context:
  name: coldtype
  version: "0.13.1"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/coldtype-${{ version }}.tar.gz
  sha256: 1876d295fd07b7031100fcb5ff1fbb9e5441fb740b6701aa1c2b27e96aab406c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - coldtype = coldtype.renderer:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61.0
    - setuptools_scm >=8.0
    - wheel
  run:
    - python >=${{ python_min }}
    - fontpens ==0.2.4
    - easing-functions ==1.0.4
    - b3denv >=0.0.22
    - coldtype-fontgoggles ==1.8.4.7
    - skia-pathops
    - defcon >=0.12.0
    - freetype-py
    - uharfbuzz <0.47.0
    - fonttools >=4.60.2
    - show-in-file-manager >=1.1.6

tests:
  - python:
      imports:
        - coldtype
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - coldtype --help

about:
  summary: Functions for manual vectorized typesetting
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/goodhertz/coldtype

extra:
  recipe-maintainers:
    - thewchan
